JFLAGS = -g
JC = javac
.SUFFIXES: .java .class
.java.class:
	$(JC) $(JFLAGS) $*.java

CLASSES = \
	hw3.java \
	Point.java \
	XComparator.java \
	YComparator.java \

default: classes

classes: $(CLASSES:.java=.class)

clean:
	$(RM) *.class